[package]
name = "sfml_rs"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "games/tetris"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.20.0"
tetris = { path = "./games/tetris/" }
